baseurl = "https://ricardogonart.github.io"
publishDir = "docs"
languageCode = "es"
title = "Blog proyecto Méliès"
theme = "hucore"
copyright = "&copy; 2017 Cristina Fernández | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥ | <a href=\"https://js.org\" target=\"_blank\" title=\"JS.ORG | JavaScript Community\"><img src=\"https://logo.js.org/dark_tiny.png\" width=\"55\" alt=\"JS.ORG Logo\"></a>"
